### ISSUE TITLE
DEPRECATION: A property of <my-app@view:-outlet::ember667> was modified inside the didInsertElement hook.

### ISSUE THREAD

**Issue by jlsuttles** [ivanvanderbyl/deluge#2]
DEPRECATION: A property of <my-app@view:-outlet::ember667> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes _significant performance degradation_. [deprecation id: ember-views.dispatching-modify-property]

**Comment by ivanvanderbyl** [comment]
Issue is resolved locally. I'll push it soon.

**Comment by jessicasuttles** [comment]
Please push! :heart:

**Comment by jessicasuttles** [comment]
Oops forgot I'm logged in with my test account. Oh well.
