### ISSUE TITLE
Menu dropdown does not stay tethered to menu button

### ISSUE THREAD

**Issue by jlsuttles** [ivanvanderbyl/deluge#3]
I am having an issue where my menu button is in a fixed header. If the dropdown is visible and the page scrolls the dropdown scrolls with the page, it does not stay tethered to the fixed button.

Also having another issue that may be related. If the page is not scrolled to the top and the menu button in the fixed header is clicked, the dropdown displays but it also scrolls the page all the way to the top.

**Comment by ivanvanderbyl** [comment]
Hi @jlsuttles, the first issue is related to us not using Tether, for the moment, which was to attempt to fix an issue calculating the position of an element using Flex Box. I think we can safely switch back to Tether.

Your second issue is actually the browser. I'm not sure on a good workaround yet, but basically when the menu opens, we send a `focus` event to the first item, or first selected item, which causes the browser to scroll to that element to make it visible.
